### ISSUE TITLE
Can't get timer to track longer than 2 min

### ISSUE THREAD

**Issue by rebelzach** [timeglass/glass#44]
I just encountered this issue where the timer stops at 2min no matter how much starting or stopping I do. Any recommendations or data I can provide you to better understand the bug?

**Comment by advdv** [comment]
Hey Zack, This is most probably because there was a faulty version published for a few hours. Please redownload and let me know if this solves it, you'll have to restart the timer `glass start/stop`. If that doesn't work feel free to reopen this issue.

Hopefully we can get up some automated tests soon so issues such as this won't happen in the future.

**Comment by rebelzach** [comment]
I'm still on 0.5.2, was trying to not be too close to the edge. Do you think using a more recent build would be better? I have three daemons running at the same time right now, but only one repo tracked, does that sound right?

I apologize for the vague feedback as time would normally allow me to look at the code to help inform what might be happening. I have to believe something on my machine changed to cause this issue. I'll let you know if a newer build works better.

**Comment by rebelzach** [comment]
Seems better with new build

**Comment by advdv** [comment]
Hey Zack, the three deamons doesn't seem to be right. Any idea what might have caused them? We should think of a way to handle these phantom timers - I've added this as a todo in the next version. Am I correct that the new version did solve the stuck at 2 mins problem?
